apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-install"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-pre-install"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "alpine"
        command: ["echo","{{ .Release.Revision }}"]
